name: simple_ci_runner
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

dependencies:
  dartssh2: ^2.8.2
  process_run: ^0.13.1
  supabase: ^1.10.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
